import { ID_FIELD, WriteConfirmation } from "firestorm-db";
import { PackID, Texture, Textures, EntireUseToCreate } from "../interfaces";
import {
	Edition,
	EntireTextureToCreate,
	TextureCreationParam,
	TextureProperty,
	PropertyToOutput,
} from "../interfaces/textures";
import TextureFirestormRepository from "../repository/texture.repository";
import PathService from "./path.service";
import UseService from "./use.service";

export default class TextureService {
	private readonly textureRepo = new TextureFirestormRepository();

	private readonly useService = new UseService();

	private readonly pathService = new PathService();

	static instance: TextureService;

	static getInstance() {
		if (!TextureService.instance) TextureService.instance = new TextureService();
		return TextureService.instance;
	}

	constructor() {
		TextureService.instance = this;
	}

	getRaw(): Promise<Record<string, Texture>> {
		return this.textureRepo.getRaw();
	}

	async getById<Property extends TextureProperty>(
		id: number,
		property: Property,
	): Promise<PropertyToOutput<Property>> {
		if (Number.isNaN(id) || id < 0) throw new Error("Texture IDs are integers greater than 0");
		return this.textureRepo.getTextureById(id, property);
	}

	getByNameIdAndTag(tag: string | undefined, search: string | undefined): Promise<Textures> {
		return this.textureRepo.getByNameIdAndTag(tag, search);
	}

	searchByNameIdAndTag(tag: string | undefined, search: string | undefined): Promise<Textures> {
		return this.textureRepo.getByNameIdAndTag(tag, search, true);
	}

	getVersions(): Promise<string[]> {
		return this.textureRepo.getVersions();
	}

	getVersionByEdition(edition: Edition): Promise<string[]> {
		return this.textureRepo.getVersionByEdition(edition);
	}

	getEditions(): Promise<string[]> {
		return this.textureRepo.getEditions();
	}

	getTags(): Promise<string[]> {
		return this.textureRepo.getTags();
	}

	getResolutions(): Promise<number[]> {
		return this.textureRepo.getResolutions();
	}

	getAnimated(): Promise<number[]> {
		return this.textureRepo.getAnimated();
	}

	async getPropertyByNameOrId<Property extends TextureProperty>(
		nameOrID: string | number,
		property: Property,
	): Promise<PropertyToOutput<Property>> {
		try {
			return await this.textureRepo.searchTexturePropertyByNameOrId<Property>(nameOrID, property);
		} catch {
			throw new Error(`Failed to search property "${property}" on texture ${nameOrID}`);
		}
	}

	// AlwaysID is a typescript hack to make sure the correct types are always returned
	getByNameOrId<AlwaysID extends boolean>(
		nameOrID: string | number,
	): Promise<AlwaysID extends true ? Texture : Texture | Textures> {
		return this.textureRepo.searchTextureByNameOrId<AlwaysID>(nameOrID);
	}

	getURLById(id: number, pack: PackID, version: string): Promise<string> {
		return this.textureRepo.getURLById(id, pack, version);
	}

	async mergeTextures(source: string, destination: string) {
		// append the uses of the source texture to the uses of the destination texture
		const { uses: usesToRemove, paths: pathsToRemove } = await this.getPropertyByNameOrId(
			source,
			"all",
		);

		// no need to delete use properties because it gets overwritten later anyways
		const usesToCreate: EntireUseToCreate[] = usesToRemove.map((use) => ({
			...use,
			paths: pathsToRemove
				.filter((p) => p.use === use[ID_FIELD])
				.map((path) => {
					delete path[ID_FIELD];
					delete path.use;
					return path;
				}),
		}));

		await this.useService.appendMultipleUses(destination, usesToCreate);
		await this.deleteTexture(source);
	}

	createTexture(texture: TextureCreationParam): Promise<Texture> {
		return this.textureRepo.createTexture(texture);
	}

	async createEntireTextures(body: EntireTextureToCreate[]): Promise<Textures> {
		// must do this before anything else to prevent id collisions
		const createdTextures = await this.textureRepo.createTexturesBulk(
			body.map((tex) => ({ name: tex.name, tags: tex.tags })),
		);

		// can be done in parallel because all autogenerated ids at this point are known
		const useResults = await Promise.all(
			// addBulk maintains key order so we can use the index reliably here
			body.map((tex, i) =>
				this.useService.generateAppendableUses(createdTextures[i][ID_FIELD], tex.uses, true),
			),
		);

		// flatMap to save requests (ids are known so we only need one request to add everything)
		await Promise.all([
			this.useService.createMultipleUses(useResults.flatMap((r) => r.usesToCreate)),
			this.pathService.createMultiplePaths(useResults.flatMap((r) => r.pathsToCreate)),
		]);

		return createdTextures;
	}

	async editTexture(id: string, body: TextureCreationParam): Promise<Texture> {
		await this.getByNameOrId(id);
		return this.textureRepo.editTexture(id, body);
	}

	deleteTexture(id: string): Promise<WriteConfirmation[]> {
		return this.textureRepo.deleteTexture(id);
	}
}
