name: Deploy API

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH }}
        script: |
          cd /var/www/html/api.faithfulpack.net/
          git stash
          git pull
          pnpm install
          pnpm build
          pm2 restart "API"
